function filename = construct_datastamped_filename(name_str, c)
% constructs a datestamped filename 
% name_str is a identifier string added at the begining of the name.
% c is a time vector such as generated by the clock function.
% 
% example filename = construct_filename('MBF', clock)

yr = num2str(c(1));
mth = num2str(c(2));
dy = num2str(c(3));
hr = num2str(c(4));
mn = num2str(c(5));
sec = num2str(round(c(6)));

if c(2) < 10
mth = ['0' mth];
end
if c(3) < 10
dy = ['0' dy];
end
if c(4) < 10
hr = ['0' hr];
end
if c(5) < 10
mn = ['0' mn];
end
if c(6) < 10
sec = ['0' sec];
end

filename = [name_str '_' dy '_' mth '_' yr '_' hr '-' mn '-' sec];